import type { StoreItem, UserLevel } from "./types"

export const storeItems: StoreItem[] = [
  // TEMAS (30 items)
  {
    id: 1,
    type: "theme",
    name: "Tema Neón",
    description: "Un tema vibrante con colores neón y efectos de brillo",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=300&h=200&fit=crop",
    cost: 50,
    data: {
      primaryColor: "#00ff88",
      secondaryColor: "#ff0088",
      accentColor: "#0088ff",
      backgroundColor: "#0a0a0a",
      gradients: "from-green-400 via-blue-500 to-purple-600",
      name: "neon",
    },
  },
  {
    id: 2,
    type: "theme",
    name: "Tema Dorado",
    description: "Elegante tema con tonos dorados y negros",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&h=200&fit=crop",
    cost: 75,
    data: {
      primaryColor: "#ffd700",
      secondaryColor: "#ffb347",
      accentColor: "#ff8c00",
      backgroundColor: "#1a1a1a",
      gradients: "from-yellow-400 via-orange-500 to-red-600",
      name: "gold",
    },
  },
  {
    id: 3,
    type: "theme",
    name: "Tema Océano",
    description: "Tema inspirado en el océano con azules profundos",
    image: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=300&h=200&fit=crop",
    cost: 60,
    data: {
      primaryColor: "#0077be",
      secondaryColor: "#00a8cc",
      accentColor: "#40e0d0",
      backgroundColor: "#001122",
      gradients: "from-blue-600 via-cyan-500 to-teal-400",
      name: "ocean",
    },
  },
  {
    id: 4,
    type: "theme",
    name: "Tema Vampiro",
    description: "Tema oscuro con rojos sangre y negros profundos",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=200&fit=crop",
    cost: 80,
    data: {
      primaryColor: "#8b0000",
      secondaryColor: "#dc143c",
      accentColor: "#ff6347",
      backgroundColor: "#0f0f0f",
      gradients: "from-red-900 via-black to-red-800",
      name: "vampire",
    },
  },
  {
    id: 5,
    type: "theme",
    name: "Tema Bosque",
    description: "Tema natural con verdes y marrones",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=300&h=200&fit=crop",
    cost: 65,
    data: {
      primaryColor: "#228b22",
      secondaryColor: "#32cd32",
      accentColor: "#90ee90",
      backgroundColor: "#0d1b0d",
      gradients: "from-green-800 via-green-900 to-black",
      name: "forest",
    },
  },
  {
    id: 6,
    type: "theme",
    name: "Tema Sunset",
    description: "Colores cálidos de atardecer",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&h=200&fit=crop",
    cost: 70,
    data: {
      primaryColor: "#ff6b35",
      secondaryColor: "#f7931e",
      accentColor: "#ffb347",
      backgroundColor: "#2d1b0f",
      gradients: "from-orange-600 via-red-500 to-pink-500",
      name: "sunset",
    },
  },
  {
    id: 7,
    type: "theme",
    name: "Tema Invierno",
    description: "Tema frío con azules y blancos",
    image: "https://images.unsplash.com/photo-1484417894907-623942c8ee29?w=300&h=200&fit=crop",
    cost: 72,
    data: {
      primaryColor: "#e6f4ff",
      secondaryColor: "#b3d9ff",
      accentColor: "#80bfff",
      backgroundColor: "#0a2940",
      gradients: "from-blue-200 via-blue-300 to-blue-400",
      name: "winter",
    },
  },
  {
    id: 8,
    type: "theme",
    name: "Tema Desierto",
    description: "Tonos cálidos y arenosos",
    image: "https://images.unsplash.com/photo-1473283437638-5a6049391666?w=300&h=200&fit=crop",
    cost: 68,
    data: {
      primaryColor: "#f0e68c",
      secondaryColor: "#d2b48c",
      accentColor: "#a0522d",
      backgroundColor: "#332927",
      gradients: "from-yellow-200 via-yellow-300 to-yellow-400",
      name: "desert",
    },
  },
  {
    id: 9,
    type: "theme",
    name: "Tema Espacial",
    description: "Inspirado en el espacio profundo",
    image: "https://images.unsplash.com/photo-1506318137070-4f2054033f0a?w=300&h=200&fit=crop",
    cost: 78,
    data: {
      primaryColor: "#4682b4",
      secondaryColor: "#778899",
      accentColor: "#b0c4de",
      backgroundColor: "#000000",
      gradients: "from-gray-700 via-gray-800 to-gray-900",
      name: "space",
    },
  },
  {
    id: 10,
    type: "theme",
    name: "Tema Retro",
    description: "Colores vibrantes de los 80",
    image: "https://images.unsplash.com/photo-1493711662062-fa19b8d2f5c6?w=300&h=200&fit=crop",
    cost: 74,
    data: {
      primaryColor: "#ff69b4",
      secondaryColor: "#ba55d3",
      accentColor: "#9370db",
      backgroundColor: "#2f4f4f",
      gradients: "from-pink-400 via-purple-500 to-indigo-600",
      name: "retro",
    },
  },
  {
    id: 11,
    type: "theme",
    name: "Tema Primavera",
    description: "Colores frescos y florales",
    image: "https://images.unsplash.com/photo-1523381294911-8cd65465899c?w=300&h=200&fit=crop",
    cost: 66,
    data: {
      primaryColor: "#98fb98",
      secondaryColor: "#90ee90",
      accentColor: "#adff2f",
      backgroundColor: "#f0fff0",
      gradients: "from-green-100 via-green-200 to-green-300",
      name: "spring",
    },
  },
  {
    id: 12,
    type: "theme",
    name: "Tema Minimalista",
    description: "Simple y elegante",
    image: "https://images.unsplash.com/photo-1488998427799-e565b47205ca?w=300&h=200&fit=crop",
    cost: 55,
    data: {
      primaryColor: "#ffffff",
      secondaryColor: "#f0f0f0",
      accentColor: "#d3d3d3",
      backgroundColor: "#000000",
      gradients: "from-gray-100 via-gray-200 to-gray-300",
      name: "minimalist",
    },
  },
  {
    id: 13,
    type: "theme",
    name: "Tema Arcoíris",
    description: "Todos los colores del arcoíris",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=300&h=200&fit=crop",
    cost: 85,
    data: {
      primaryColor: "#ff0000",
      secondaryColor: "#ffa500",
      accentColor: "#ffff00",
      backgroundColor: "#ffffff",
      gradients: "from-red-500 via-yellow-500 to-green-500",
      name: "rainbow",
    },
  },
  {
    id: 14,
    type: "theme",
    name: "Tema Café",
    description: "Tonos cálidos de café",
    image: "https://images.unsplash.com/photo-1495474472285-6d0ba4df95ad?w=300&h=200&fit=crop",
    cost: 62,
    data: {
      primaryColor: "#a0522d",
      secondaryColor: "#d2b48c",
      accentColor: "#f4a460",
      backgroundColor: "#222222",
      gradients: "from-brown-400 via-brown-500 to-brown-600",
      name: "coffee",
    },
  },
  {
    id: 15,
    type: "theme",
    name: "Tema Menta",
    description: "Refrescante y suave",
    image: "https://images.unsplash.com/photo-1558024550-c1a9a05f06ca?w=300&h=200&fit=crop",
    cost: 58,
    data: {
      primaryColor: "#98ff98",
      secondaryColor: "#aaffc3",
      accentColor: "#bfff00",
      backgroundColor: "#f5fffa",
      gradients: "from-green-200 via-green-300 to-green-400",
      name: "mint",
    },
  },
  {
    id: 16,
    type: "theme",
    name: "Tema Lavanda",
    description: "Relajante y floral",
    image: "https://images.unsplash.com/photo-1501600863863-955c95a9419b?w=300&h=200&fit=crop",
    cost: 64,
    data: {
      primaryColor: "#e6e6fa",
      secondaryColor: "#d8bfd8",
      accentColor: "#dda0dd",
      backgroundColor: "#f8f8ff",
      gradients: "from-purple-100 via-purple-200 to-purple-300",
      name: "lavender",
    },
  },
  {
    id: 17,
    type: "theme",
    name: "Tema Cítrico",
    description: "Vibrante y energético",
    image: "https://images.unsplash.com/photo-1559563362-c6651191c996?w=300&h=200&fit=crop",
    cost: 76,
    data: {
      primaryColor: "#ffff00",
      secondaryColor: "#ffef00",
      accentColor: "#f0e68c",
      backgroundColor: "#f5f5dc",
      gradients: "from-yellow-300 via-yellow-400 to-yellow-500",
      name: "citrus",
    },
  },
  {
    id: 18,
    type: "theme",
    name: "Tema Medianoche",
    description: "Profundo y misterioso",
    image: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=300&h=200&fit=crop",
    cost: 82,
    data: {
      primaryColor: "#191970",
      secondaryColor: "#000080",
      accentColor: "#4682b4",
      backgroundColor: "#000000",
      gradients: "from-blue-800 via-blue-900 to-black",
      name: "midnight",
    },
  },
  {
    id: 19,
    type: "theme",
    name: "Tema Coral",
    description: "Cálido y tropical",
    image: "https://images.unsplash.com/photo-1546842990-c0a22434499d?w=300&h=200&fit=crop",
    cost: 71,
    data: {
      primaryColor: "#ff7f50",
      secondaryColor: "#fa8072",
      accentColor: "#e9967a",
      backgroundColor: "#fffafa",
      gradients: "from-orange-300 via-orange-400 to-orange-500",
      name: "coral",
    },
  },
  {
    id: 20,
    type: "theme",
    name: "Tema Ártico",
    description: "Frío y puro",
    image: "https://images.unsplash.com/photo-1483729558043-7a33e5723f52?w=300&h=200&fit=crop",
    cost: 69,
    data: {
      primaryColor: "#e0ffff",
      secondaryColor: "#add8e6",
      accentColor: "#87ceeb",
      backgroundColor: "#f0ffff",
      gradients: "from-cyan-100 via-cyan-200 to-cyan-300",
      name: "arctic",
    },
  },
  {
    id: 21,
    type: "theme",
    name: "Tema Selva",
    description: "Exuberante y vibrante",
    image: "https://images.unsplash.com/photo-1470163053537-d925f1644244?w=300&h=200&fit=crop",
    cost: 73,
    data: {
      primaryColor: "#008000",
      secondaryColor: "#32cd32",
      accentColor: "#90ee90",
      backgroundColor: "#006400",
      gradients: "from-green-600 via-green-700 to-green-800",
      name: "jungle",
    },
  },
  {
    id: 22,
    type: "theme",
    name: "Tema Ópalo",
    description: "Iridescente y mágico",
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=300&h=200&fit=crop",
    cost: 88,
    data: {
      primaryColor: "#a8a8a8",
      secondaryColor: "#c0c0c0",
      accentColor: "#d3d3d3",
      backgroundColor: "#000000",
      gradients: "from-gray-400 via-gray-500 to-gray-600",
      name: "opal",
    },
  },
  {
    id: 23,
    type: "theme",
    name: "Tema Cereza",
    description: "Dulce y vibrante",
    image: "https://images.unsplash.com/photo-1558024550-c1a9a05f06ca?w=300&h=200&fit=crop",
    cost: 77,
    data: {
      primaryColor: "#ff0000",
      secondaryColor: "#dc143c",
      accentColor: "#ff6347",
      backgroundColor: "#f08080",
      gradients: "from-red-400 via-red-500 to-red-600",
      name: "cherry",
    },
  },
  {
    id: 24,
    type: "theme",
    name: "Tema Naranja",
    description: "Energético y cálido",
    image: "https://images.unsplash.com/photo-1558024550-c1a9a05f06ca?w=300&h=200&fit=crop",
    cost: 75,
    data: {
      primaryColor: "#ffa500",
      secondaryColor: "#ff8c00",
      accentColor: "#ff7f50",
      backgroundColor: "#ffe4b5",
      gradients: "from-orange-400 via-orange-500 to-orange-600",
      name: "orange",
    },
  },
  {
    id: 25,
    type: "theme",
    name: "Tema Oliva",
    description: "Natural y suave",
    image: "https://images.unsplash.com/photo-1558024550-c1a9a05f06ca?w=300&h=200&fit=crop",
    cost: 67,
    data: {
      primaryColor: "#808000",
      secondaryColor: "#a0a000",
      accentColor: "#c0c000",
      backgroundColor: "#f5f5dc",
      gradients: "from-yellow-700 via-yellow-800 to-yellow-900",
      name: "olive",
    },
  },
  {
    id: 26,
    type: "theme",
    name: "Tema Platino",
    description: "Elegante y brillante",
    image: "https://images.unsplash.com/photo-1558024550-c1a9a05f06ca?w=300&h=200&fit=crop",
    cost: 90,
    data: {
      primaryColor: "#e5e4e2",
      secondaryColor: "#d3d0cb",
      accentColor: "#c0c0c0",
      backgroundColor: "#000000",
      gradients: "from-gray-200 via-gray-300 to-gray-400",
      name: "platinum",
    },
  },
  {
    id: 27,
    type: "theme",
    name: "Tema Amatista",
    description: "Místico y profundo",
    image: "https://images.unsplash.com/photo-1558024550-c1a9a05f06ca?w=300&h=200&fit=crop",
    cost: 81,
    data: {
      primaryColor: "#9966cc",
      secondaryColor: "#800080",
      accentColor: "#9370db",
      backgroundColor: "#f8f8ff",
      gradients: "from-purple-500 via-purple-600 to-purple-700",
      name: "amethyst",
    },
  },
  {
    id: 28,
    type: "theme",
    name: "Tema Turquesa",
    description: "Refrescante y tropical",
    image: "https://images.unsplash.com/photo-1558024550-c1a9a05f06ca?w=300&h=200&fit=crop",
    cost: 79,
    data: {
      primaryColor: "#40e0d0",
      secondaryColor: "#00ced1",
      accentColor: "#48d1cc",
      backgroundColor: "#f0ffff",
      gradients: "from-cyan-400 via-cyan-500 to-cyan-600",
      name: "turquoise",
    },
  },
  {
    id: 29,
    type: "theme",
    name: "Tema Chocolate",
    description: "Delicioso y cálido",
    image: "https://images.unsplash.com/photo-1558024550-c1a9a05f06ca?w=300&h=200&fit=crop",
    cost: 63,
    data: {
      primaryColor: "#7b3f00",
      secondaryColor: "#a0522d",
      accentColor: "#d2691e",
      backgroundColor: "#f5f5dc",
      gradients: "from-brown-700 via-brown-800 to-brown-900",
      name: "chocolate",
    },
  },
  {
    id: 30,
    type: "theme",
    name: "Tema Esmeralda",
    description: "Elegante y natural",
    image: "https://images.unsplash.com/photo-1558024550-c1a9a05f06ca?w=300&h=200&fit=crop",
    cost: 84,
    data: {
      primaryColor: "#50c878",
      secondaryColor: "#008000",
      accentColor: "#228b22",
      backgroundColor: "#f0fff0",
      gradients: "from-green-300 via-green-400 to-green-500",
      name: "emerald",
    },
  },

  // EMOTES (30 items)
  {
    id: 31,
    type: "emote",
    name: "Corazón Brillante",
    description: "Un corazón con efectos de brillo",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+💖PC90ZXh0Pgo8L3N2Zz4=",
    cost: 15,
    data: { emoji: "💖", code: ":sparkle_heart:" },
  },
  {
    id: 32,
    type: "emote",
    name: "Fuego",
    description: "Emote de fuego para comentarios intensos",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🔥PC90ZXh0Pgo8L3N2Zz4=",
    cost: 10,
    data: { emoji: "🔥", code: ":fire:" },
  },
  {
    id: 33,
    type: "emote",
    name: "Risa",
    description: "Emote de risa contagiosa",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😂PC90ZXh0Pgo8L3N2Zz4=",
    cost: 12,
    data: { emoji: "😂", code: ":joy:" },
  },
  {
    id: 34,
    type: "emote",
    name: "Pulgar Arriba",
    description: "Emote de aprobación",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+👍PC90ZXh0Pgo8L3N2Zz4=",
    cost: 8,
    data: { emoji: "👍", code: ":thumbs_up:" },
  },
  {
    id: 35,
    type: "emote",
    name: "Sorpresa",
    description: "Emote de asombro",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😮PC90ZXh0Pgo8L3N2Zz4=",
    cost: 11,
    data: { emoji: "😮", code: ":open_mouth:" },
  },
  {
    id: 36,
    type: "emote",
    name: "Pensando",
    description: "Emote de reflexión",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🤔PC90ZXh0Pgo8L3N2Zz4=",
    cost: 13,
    data: { emoji: "🤔", code: ":thinking:" },
  },
  {
    id: 37,
    type: "emote",
    name: "Guiño",
    description: "Emote de complicidad",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😉PC90ZXh0Pgo8L3N2Zz4=",
    cost: 9,
    data: { emoji: "😉", code: ":wink:" },
  },
  {
    id: 38,
    type: "emote",
    name: "Llorando",
    description: "Emote de tristeza",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😢PC90ZXh0Pgo8L3N2Zz4=",
    cost: 10,
    data: { emoji: "😢", code: ":cry:" },
  },
  {
    id: 39,
    type: "emote",
    name: "Enfadado",
    description: "Emote de ira",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😠PC90ZXh0Pgo8L3N2Zz4=",
    cost: 14,
    data: { emoji: "😠", code: ":angry:" },
  },
  {
    id: 40,
    type: "emote",
    name: "Confundido",
    description: "Emote de perplejidad",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😕PC90ZXh0Pgo8L3N2Zz4=",
    cost: 11,
    data: { emoji: "😕", code: ":confused:" },
  },
  {
    id: 41,
    type: "emote",
    name: "Sonrojado",
    description: "Emote de timidez",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😊PC90ZXh0Pgo8L3N2Zz4=",
    cost: 12,
    data: { emoji: "😊", code: ":blush:" },
  },
  {
    id: 42,
    type: "emote",
    name: "Mareado",
    description: "Emote de vértigo",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😵PC90ZXh0Pgo8L3N2Zz4=",
    cost: 13,
    data: { emoji: "😵", code: ":dizzy_face:" },
  },
  {
    id: 43,
    type: "emote",
    name: "Relajado",
    description: "Emote de tranquilidad",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😌PC90ZXh0Pgo8L3N2Zz4=",
    cost: 10,
    data: { emoji: "😌", code: ":relieved:" },
  },
  {
    id: 44,
    type: "emote",
    name: "Malvado",
    description: "Emote de travesura",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😈PC90ZXh0Pgo8L3N2Zz4=",
    cost: 15,
    data: { emoji: "😈", code: ":smiling_imp:" },
  },
  {
    id: 45,
    type: "emote",
    name: "Ángel",
    description: "Emote de bondad",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😇PC90ZXh0Pgo8L3N2Zz4=",
    cost: 14,
    data: { emoji: "😇", code: ":innocent:" },
  },
  {
    id: 46,
    type: "emote",
    name: "Cara de Beso",
    description: "Emote de afecto",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+😘PC90ZXh0Pgo8L3N2Zz4=",
    cost: 12,
    data: { emoji: "😘", code: ":kissing_heart:" },
  },
  {
    id: 47,
    type: "emote",
    name: "Cara de Dinero",
    description: "Emote de riqueza",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🤑PC90ZXh0Pgo8L3N2Zz4=",
    cost: 16,
    data: { emoji: "🤑", code: ":money_mouth_face:" },
  },
  {
    id: 48,
    type: "emote",
    name: "Cara de Nerd",
    description: "Emote de inteligencia",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🤓PC90ZXh0Pgo8L3N2Zz4=",
    cost: 13,
    data: { emoji: "🤓", code: ":nerd_face:" },
  },
  {
    id: 49,
    type: "emote",
    name: "Cara de Payaso",
    description: "Emote de diversión",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🤡PC90ZXh0Pgo8L3N2Zz4=",
    cost: 11,
    data: { emoji: "🤡", code: ":clown_face:" },
  },
  {
    id: 50,
    type: "emote",
    name: "Cara de Robot",
    description: "Emote de tecnología",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🤖PC90ZXh0Pgo8L3N2Zz4=",
    cost: 14,
    data: { emoji: "🤖", code: ":robot_face:" },
  },
  {
    id: 51,
    type: "emote",
    name: "Fantasma",
    description: "Emote de miedo",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+👻PC90ZXh0Pgo8L3N2Zz4=",
    cost: 12,
    data: { emoji: "👻", code: ":ghost:" },
  },
  {
    id: 52,
    type: "emote",
    name: "Calavera",
    description: "Emote de peligro",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+💀PC90ZXh0Pgo8L3N2Zz4=",
    cost: 13,
    data: { emoji: "💀", code: ":skull:" },
  },
  {
    id: 53,
    type: "emote",
    name: "Bomba",
    description: "Emote de explosión",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+💣PC90ZXh0Pgo8L3N2Zz4=",
    cost: 15,
    data: { emoji: "💣", code: ":bomb:" },
  },
  {
    id: 54,
    type: "emote",
    name: "Cuchillo",
    description: "Emote de peligro",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🔪PC90ZXh0Pgo8L3N2Zz4=",
    cost: 14,
    data: { emoji: "🔪", code: ":knife:" },
  },
  {
    id: 55,
    type: "emote",
    name: "Pistola",
    description: "Emote de acción",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🔫PC90ZXh0Pgo8L3N2Zz4=",
    cost: 16,
    data: { emoji: "🔫", code: ":gun:" },
  },
  {
    id: 56,
    type: "emote",
    name: "Microbio",
    description: "Emote de enfermedad",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🦠PC90ZXh0Pgo8L3N2Zz4=",
    cost: 10,
    data: { emoji: "🦠", code: ":microbe:" },
  },
  {
    id: 57,
    type: "emote",
    name: "Corazón Roto",
    description: "Emote de desamor",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+💔PC90ZXh0Pgo8L3N2Zz4=",
    cost: 13,
    data: { emoji: "💔", code: ":broken_heart:" },
  },
  {
    id: 58,
    type: "emote",
    name: "Exclamación",
    description: "Emote de énfasis",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+❗PC90ZXh0Pgo8L3N2Zz4=",
    cost: 11,
    data: { emoji: "❗", code: ":exclamation:" },
  },
  {
    id: 59,
    type: "emote",
    name: "Interrogación",
    description: "Emote de duda",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+❓PC90ZXh0Pgo8L3N2Zz4=",
    cost: 10,
    data: { emoji: "❓", code: ":question:" },
  },
  {
    id: 60,
    type: "emote",
    name: "Silencio",
    description: "Emote de discreción",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMzMzIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSI0MCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+🤫PC90ZXh0Pgo8L3N2Zz4=",
    cost: 12,
    data: { emoji: "🤫", code: ":shushing_face:" },
  },

  // AVATARES (30 items)
  {
    id: 61,
    type: "avatar",
    name: "Avatar Cyberpunk",
    description: "Avatar futurista estilo cyberpunk",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Cyberpunk&accessories=sunglasses&clothingColor=262e33&eyebrowType=raisedExcited&eyeType=wink&facialHairColor=auburn&facialHairType=beardMedium&hairColor=silverGray&hatColor=black&mouthType=smile&skinColor=light&topType=hat",
    cost: 30,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Cyberpunk&accessories=sunglasses&clothingColor=262e33&eyebrowType=raisedExcited&eyeType=wink&facialHairColor=auburn&facialHairType=beardMedium&hairColor=silverGray&hatColor=black&mouthType=smile&skinColor=light&topType=hat",
    },
  },
  {
    id: 62,
    type: "avatar",
    name: "Avatar Ninja",
    description: "Avatar misterioso estilo ninja",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Ninja&clothingColor=black&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=serious&skinColor=light&topType=winterHat2",
    cost: 25,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ninja&clothingColor=black&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=serious&skinColor=light&topType=winterHat2",
    },
  },
  {
    id: 63,
    type: "avatar",
    name: "Avatar Rockstar",
    description: "Avatar con estilo rockstar",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Rockstar&accessories=sunglasses&clothingColor=black&eyebrowType=default&eyeType=default&facialHairColor=black&facialHairType=goatee&hairColor=black&mouthType=smile&skinColor=light&topType=longHairStraight",
    cost: 35,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rockstar&accessories=sunglasses&clothingColor=black&eyebrowType=default&eyeType=default&facialHairColor=black&facialHairType=goatee&hairColor=black&mouthType=smile&skinColor=light&topType=longHairStraight",
    },
  },
  {
    id: 64,
    type: "avatar",
    name: "Avatar Princesa",
    description: "Avatar elegante estilo princesa",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Princess&clothingColor=pink&eyebrowType=default&eyeType=happy&hairColor=blonde&mouthType=smile&skinColor=light&topType=longHairCurly&accessoriesType=blank",
    cost: 40,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Princess&clothingColor=pink&eyebrowType=default&eyeType=happy&hairColor=blonde&mouthType=smile&skinColor=light&topType=longHairCurly&accessoriesType=blank",
    },
  },
  {
    id: 65,
    type: "avatar",
    name: "Avatar Científico",
    description: "Avatar intelectual estilo científico",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Scientist&accessories=prescription02&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    cost: 28,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Scientist&accessories=prescription02&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    },
  },
  {
    id: 66,
    type: "avatar",
    name: "Avatar Vaquero",
    description: "Avatar con estilo del viejo oeste",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Cowboy&accessories=sunglasses&clothingColor=blue03&eyebrowType=default&eyeType=default&facialHairType=beardLight&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortWaved",
    cost: 32,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Cowboy&accessories=sunglasses&clothingColor=blue03&eyebrowType=default&eyeType=default&facialHairType=beardLight&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortWaved",
    },
  },
  {
    id: 67,
    type: "avatar",
    name: "Avatar Mago",
    description: "Avatar con poderes mágicos",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Wizard&clothingColor=purple&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=gray&mouthType=smile&skinColor=light&topType=turban",
    cost: 38,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Wizard&clothingColor=purple&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=gray&mouthType=smile&skinColor=light&topType=turban",
    },
  },
  {
    id: 68,
    type: "avatar",
    name: "Avatar Zombie",
    description: "Avatar terrorífico estilo zombie",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Zombie&clothingColor=green01&eyebrowType=default&eyeType=squint&facialHairType=blank&hairColor=green&mouthType=disbelief&skinColor=green&topType=shortHairDreads",
    cost: 27,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zombie&clothingColor=green01&eyebrowType=default&eyeType=squint&facialHairType=blank&hairColor=green&mouthType=disbelief&skinColor=green&topType=shortHairDreads",
    },
  },
  {
    id: 69,
    type: "avatar",
    name: "Avatar Pirata",
    description: "Avatar aventurero estilo pirata",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Pirate&accessories=eyepatch&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=beardMedium&hairColor=black&mouthType=smile&skinColor=light&topType=hat",
    cost: 33,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pirate&accessories=eyepatch&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=beardMedium&hairColor=black&mouthType=smile&skinColor=light&topType=hat",
    },
  },
  {
    id: 70,
    type: "avatar",
    name: "Avatar Astronauta",
    description: "Avatar explorador del espacio",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Astronaut&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=blonde&mouthType=smile&skinColor=light&topType=hijab",
    cost: 42,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Astronaut&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=blonde&mouthType=smile&skinColor=light&topType=hijab",
    },
  },
  {
    id: 71,
    type: "avatar",
    name: "Avatar Detective",
    description: "Avatar con estilo de detective clásico",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Detective&accessories=prescription01&clothingColor=gray01&eyebrowType=default&eyeType=default&facialHairType=moustacheMagnum&hairColor=brown&mouthType=smile&skinColor=light&topType=hat",
    cost: 31,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Detective&accessories=prescription01&clothingColor=gray01&eyebrowType=default&eyeType=default&facialHairType=moustacheMagnum&hairColor=brown&mouthType=smile&skinColor=light&topType=hat",
    },
  },
  {
    id: 72,
    type: "avatar",
    name: "Avatar Chef",
    description: "Avatar con estilo de chef profesional",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Chef&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=chefHat",
    cost: 36,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chef&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=chefHat",
    },
  },
  {
    id: 73,
    type: "avatar",
    name: "Avatar Deportista",
    description: "Avatar con estilo de atleta",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Athlete&accessories=sport01&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    cost: 29,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Athlete&accessories=sport01&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    },
  },
  {
    id: 74,
    type: "avatar",
    name: "Avatar Granjero",
    description: "Avatar con estilo de granjero",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Farmer&clothingColor=green03&eyebrowType=default&eyeType=default&facialHairType=beardLight&hairColor=gray&mouthType=smile&skinColor=light&topType=hat",
    cost: 26,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Farmer&clothingColor=green03&eyebrowType=default&eyeType=default&facialHairType=beardLight&hairColor=gray&mouthType=smile&skinColor=light&topType=hat",
    },
  },
  {
    id: 75,
    type: "avatar",
    name: "Avatar Artista",
    description: "Avatar con estilo de pintor",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Artist&accessories=roundGlasses&clothingColor=orange&eyebrowType=default&eyeType=default&facialHairType=beardMedium&hairColor=black&mouthType=smile&skinColor=light&topType=longHairBob",
    cost: 34,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Artist&accessories=roundGlasses&clothingColor=orange&eyebrowType=default&eyeType=default&facialHairType=beardMedium&hairColor=black&mouthType=smile&skinColor=light&topType=longHairBob",
    },
  },
  {
    id: 76,
    type: "avatar",
    name: "Avatar Musico",
    description: "Avatar con estilo de músico",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Musician&accessories=headphones&clothingColor=blue03&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairDreads",
    cost: 37,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Musician&accessories=headphones&clothingColor=blue03&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairDreads",
    },
  },
  {
    id: 77,
    type: "avatar",
    name: "Avatar Programador",
    description: "Avatar con estilo de desarrollador",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Programmer&accessories=prescription02&clothingColor=gray01&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    cost: 39,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Programmer&accessories=prescription02&clothingColor=gray01&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    },
  },
  {
    id: 78,
    type: "avatar",
    name: "Avatar Profesor",
    description: "Avatar con estilo de maestro",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Teacher&accessories=roundGlasses&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=gray&mouthType=smile&skinColor=light&topType=shortHairTheCaesar",
    cost: 41,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Teacher&accessories=roundGlasses&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=gray&mouthType=smile&skinColor=light&topType=shortHairTheCaesar",
    },
  },
  {
    id: 79,
    type: "avatar",
    name: "Avatar Abogado",
    description: "Avatar con estilo de jurista",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Lawyer&accessories=prescription02&clothingColor=blue03&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    cost: 43,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lawyer&accessories=prescription02&clothingColor=blue03&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    },
  },
  {
    id: 80,
    type: "avatar",
    name: "Avatar Doctor",
    description: "Avatar con estilo de médico",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Doctor&accessories=prescription02&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    cost: 44,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Doctor&accessories=prescription02&clothingColor=white&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    },
  },
  {
    id: 81,
    type: "avatar",
    name: "Avatar Bombero",
    description: "Avatar con estilo de bombero",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Firefighter&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=helmet",
    cost: 45,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Firefighter&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=helmet",
    },
  },
  {
    id: 82,
    type: "avatar",
    name: "Avatar Policía",
    description: "Avatar con estilo de oficial de policía",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Police&clothingColor=blue04&eyebrowType=default&eyeType=default&facialHairType=moustacheMagnum&hairColor=brown&mouthType=smile&skinColor=light&topType=hat",
    cost: 46,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Police&clothingColor=blue04&eyebrowType=default&eyeType=default&facialHairType=moustacheMagnum&hairColor=brown&mouthType=smile&skinColor=light&topType=hat",
    },
  },
  {
    id: 83,
    type: "avatar",
    name: "Avatar Militar",
    description: "Avatar con estilo de soldado",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Military&clothingColor=camo&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    cost: 47,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Military&clothingColor=camo&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=brown&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    },
  },
  {
    id: 84,
    type: "avatar",
    name: "Avatar Espía",
    description: "Avatar con estilo de agente secreto",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Spy&accessories=sunglasses&clothingColor=black&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    cost: 48,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Spy&accessories=sunglasses&clothingColor=black&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    },
  },
  {
    id: 85,
    type: "avatar",
    name: "Avatar Superhéroe",
    description: "Avatar con estilo de defensor",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Superhero&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    cost: 49,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Superhero&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=shortHairShortFlat",
    },
  },
  {
    id: 86,
    type: "avatar",
    name: "Avatar Vikingo",
    description: "Avatar con estilo de guerrero nórdico",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Viking&clothingColor=brown&eyebrowType=default&eyeType=default&facialHairType=beardMedium&hairColor=blonde&mouthType=smile&skinColor=light&topType=hat",
    cost: 50,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Viking&clothingColor=brown&eyebrowType=default&eyeType=default&facialHairType=beardMedium&hairColor=blonde&mouthType=smile&skinColor=light&topType=hat",
    },
  },
  {
    id: 87,
    type: "avatar",
    name: "Avatar Samurai",
    description: "Avatar con estilo de guerrero japonés",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Samurai&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=samuraiHelmet",
    cost: 51,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Samurai&clothingColor=red&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=samuraiHelmet",
    },
  },
  {
    id: 88,
    type: "avatar",
    name: "Avatar Monje",
    description: "Avatar con estilo de religioso",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Monk&clothingColor=orange&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=turban",
    cost: 52,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Monk&clothingColor=orange&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=black&mouthType=smile&skinColor=light&topType=turban",
    },
  },
  {
    id: 89,
    type: "avatar",
    name: "Avatar Robot",
    description: "Avatar con estilo de máquina",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Robot&clothingColor=gray01&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=silverGray&mouthType=smile&skinColor=light&topType=hat",
    cost: 53,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robot&clothingColor=gray01&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=silverGray&mouthType=smile&skinColor=light&topType=hat",
    },
  },
  {
    id: 90,
    type: "avatar",
    name: "Avatar Alien",
    description: "Avatar con estilo de extraterrestre",
    image:
      "https://api.dicebear.com/7.x/avataaars/svg?seed=Alien&clothingColor=green01&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=green&mouthType=smile&skinColor=green&topType=shortHairDreads",
    cost: 54,
    data: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alien&clothingColor=green01&eyebrowType=default&eyeType=default&facialHairType=blank&hairColor=green&mouthType=smile&skinColor=green&topType=shortHairDreads",
    },
  },

  // OTROS (30 items - insignias, marcos, etc.)
  {
    id: 91,
    type: "other",
    name: "Insignia VIP",
    description: "Insignia especial que aparece junto a tu nombre",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZkNzAwIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSIxNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iYmxhY2siPldJUDwvdGV4dD4KPC9zdmc+",
    cost: 100,
    data: { badge: "VIP", color: "#ffd700", type: "badge" },
  },
  {
    id: 92,
    type: "other",
    name: "Marco Dorado",
    description: "Marco dorado para tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZkNzAwIiBzdHJva2U9IiNmZmI3MDAiIHN0cm9rZS13aWR0aD0iNCIvPgo8dGV4dCB4PSI1MCIgeT0iNjAiIGZvbnQtc2l6ZT0iMTIiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9ImJsYWNrIj5GUkFNRTwvdGV4dD4KPC9zdmc+",
    cost: 80,
    data: { frameType: "gold", frameColor: "#ffd700", type: "frame" },
  },
  {
    id: 93,
    type: "other",
    name: "Insignia Premium",
    description: "Insignia para usuarios especiales",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMDA3YWNjIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSIxNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iYmxhY2siPlBSRTwvdGV4dD4KPC9zdmc+",
    cost: 120,
    data: { badge: "Premium", color: "#007acc", type: "badge" },
  },
  {
    id: 94,
    type: "other",
    name: "Marco Plateado",
    description: "Marco plateado para tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjYzhjOGM4IiBzdHJva2U9IiNhOGE4YTgiIHN0cm9rZS13aWR0aD0iNCIvPgo8dGV4dCB4PSI1MCIgeT0iNjAiIGZvbnQtc2l6ZT0iMTIiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9ImJsYWNrIj5GUkFNRTwvdGV4dD4KPC9zdmc+",
    cost: 70,
    data: { frameType: "silver", frameColor: "#c0c0c0", type: "frame" },
  },
  {
    id: 95,
    type: "other",
    name: "Insignia Legendaria",
    description: "Insignia para usuarios de alto nivel",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmY0NTgwIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSIxNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iYmxhY2siPkxFRzwvdGV4dD4KPC9zdmc+",
    cost: 150,
    data: { badge: "Legend", color: "#ff4500", type: "badge" },
  },
  {
    id: 96,
    type: "other",
    name: "Marco Bronce",
    description: "Marco de bronce para tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjY2Q3ZjMyIiBzdHJva2U9IiNiODczMzMiIHN0cm9rZS13aWR0aD0iNCIvPgo8dGV4dCB4PSI1MCIgeT0iNjAiIGZvbnQtc2l6ZT0iMTIiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9ImJsYWNrIj5GUkFNRTwvdGV4dD4KPC9zdmc+",
    cost: 60,
    data: { frameType: "bronze", frameColor: "#cd7f32", type: "frame" },
  },
  {
    id: 97,
    type: "other",
    name: "Insignia Diamante",
    description: "Insignia para usuarios exclusivos",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjYjlmMmZmIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSIxNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iYmxhY2siPkRJQTwvdGV4dD4KPC9zdmc+",
    cost: 200,
    data: { badge: "Diamond", color: "#b9f2ff", type: "badge" },
  },
  {
    id: 98,
    type: "other",
    name: "Marco Esmeralda",
    description: "Marco esmeralda para tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjNWZjZjUwIiBzdHJva2U9IiM0MGU0NDAiIHN0cm9rZS13aWR0aD0iNCIvPgo8dGV4dCB4PSI1MCIgeT0iNjAiIGZvbnQtc2l6ZT0iMTIiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9ImJsYWNrIj5GUkFNRTwvdGV4dD4KPC9zdmc+",
    cost: 90,
    data: { frameType: "emerald", frameColor: "#50c878", type: "frame" },
  },
  {
    id: 99,
    type: "other",
    name: "Insignia Platino",
    description: "Insignia para usuarios de élite",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZTFlZmY1Ii8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSIxNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iYmxhY2siPlBMVDwvdGV4dD4KPC9zdmc+",
    cost: 180,
    data: { badge: "Platinum", color: "#e5e4e2", type: "badge" },
  },
  {
    id: 100,
    type: "other",
    name: "Marco Zafiro",
    description: "Marco zafiro para tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMDhiNGZmIiBzdHJva2U9IiMwMDY2Y2MiIHN0cm9rZS13aWR0aD0iNCIvPgo8dGV4dCB4PSI1MCIgeT0iNjAiIGZvbnQtc2l6ZT0iMTIiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9ImJsYWNrIj5GUkFNRTwvdGV4dD4KPC9zdmc+",
    cost: 100,
    data: { frameType: "sapphire", frameColor: "#0f52ba", type: "frame" },
  },
  {
    id: 101,
    type: "other",
    name: "Insignia Rubí",
    description: "Insignia para usuarios apasionados",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZTQwMDQxIi8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSIxNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iYmxhY2siPlJVSjwvdGV4dD4KPC9zdmc+",
    cost: 160,
    data: { badge: "Ruby", color: "#e0115f", type: "badge" },
  },
  {
    id: 102,
    type: "other",
    name: "Marco Amatista",
    description: "Marco amatista para tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjOTk2NmNjIiBzdHJva2U9IiM4MDAwODAiIHN0cm9rZS13aWR0aD0iNCIvPgo8dGV4dCB4PSI1MCIgeT0iNjAiIGZvbnQtc2l6ZT0iMTIiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9ImJsYWNrIj5GUkFNRTwvdGV4dD4KPC9zdmc+",
    cost: 85,
    data: { frameType: "amethyst", frameColor: "#9966cc", type: "frame" },
  },
  {
    id: 103,
    type: "other",
    name: "Insignia Jade",
    description: "Insignia para usuarios con estilo",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMDA5OTY2Ii8+Cjx0ZXh0IHg9IjUwIiB5PSI2MCIgZm9udC1zaXplPSIxNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iYmxhY2siPkpBREU8L3RleHQ+Cjwvc3ZnPg==",
    cost: 140,
    data: { badge: "Jade", color: "#009966", type: "badge" },
  },
  {
    id: 104,
    type: "other",
    name: "Marco Ópalo",
    description: "Marco ópalo para tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjYThhOGE4IiBzdHJva2U9IiNjMGQwYzAiIHN0cm9rZS13aWR0aD0iNCIvPgo8dGV4dCB4PSI1MCIgeT0iNjAiIGZvbnQtc2l6ZT0iMTIiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9ImJsYWNrIj5GUkFNRTwvdGV4dD4KPC9zdmc+",
    cost: 110,
    data: { frameType: "opal", frameColor: "#a8a8a8", type: "frame" },
  },
  {
    id: 105,
    type: "other",
    name: "Efecto de Brillo",
    description: "Agrega un efecto de brillo a tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZlMGJkIi8+CjxjaXJjbGUgY3g9IjUwIiBjeT0iNTAiIHI9IjMwIiBmaWxsPSIjZmZmIi8+PC9zdmc+",
    cost: 95,
    data: { effectType: "glow", effectColor: "#ffffe0", type: "effect" },
  },
  {
    id: 106,
    type: "other",
    name: "Efecto de Sombra",
    description: "Agrega una sombra sutil a tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjYmNjY2NjIi8+PGVsbGlwc2UgY3g9IjUwIiBjeT0iNTAiIHJ4PSIzMCIgcnk9IjIwIiBmaWxsPSIjMDAwIiBmaWxsLW9wYWNpdHk9IjAuMzUiLz48L3N2Zz4=",
    cost: 85,
    data: { effectType: "shadow", effectColor: "#808080", type: "effect" },
  },
  {
    id: 107,
    type: "other",
    name: "Fondo Estrellado",
    description: "Un fondo estrellado para tu perfil",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMDAwMDAwIi8+PGNpcmNsZSBjeD0iMjAiIGN5PSIyMCIgcj0iMiIgZmlsbD0iI2ZmZiIvPjxjaXJjbGUgY3g9IjgwIiBjeT0iNzUiIHI9IjMiIGZpbGw9IiNmZmYiLz48cmVjdCB4PSIwIiB5PSIwIiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0idXJsKCNpbWFnZTApIi8+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJncmFkaWVudCIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPjxzdG9wIG9mZnNldD0iMCUiIHN0b3AtY29sb3I9IiMwMDAwMDAiLz48c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiMzMzMiLz48L2xpbmVhckdyYWRpZW50PjwvZGVmcz48L3N2Zz4=",
    cost: 130,
    data: { backgroundType: "stars", backgroundColor: "#000000", type: "background" },
  },
  {
    id: 108,
    type: "other",
    name: "Fondo Abstracto",
    description: "Un fondo abstracto y moderno para tu perfil",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZmZmZmIi8+PHBhdGggZD0iTTQ1LjQ1NDUgMC4wMDAwMDFMMTAwIDU0LjU0NTVWMTBMMCAxMFYwLjAwMDAwMUw0NS40NTQ1IDAuMDAwMDAxWiIgZmlsbD0iIzAwNzhmZiIvPjwvc3ZnPg==",
    cost: 120,
    data: { backgroundType: "abstract", backgroundColor: "#ffffff", type: "background" },
  },
  {
    id: 109,
    type: "other",
    name: "Texto Personalizado",
    description: "Agrega un texto personalizado a tu perfil",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZmZmZmIi8+PHRleHQgeD0iNTAiIHk9IjYwIiBmb250LXNpemU9IjE0IiB0ZXh0LWFuY2hvciA9Im1pZGRsZSIgZmlsbD0iIzAwMDAwMCI+VGV4dG88L3RleHQ+PC9zdmc+",
    cost: 115,
    data: { textType: "custom", textColor: "#000000", type: "text" },
  },
  {
    id: 110,
    type: "other",
    name: "Borde Neon",
    description: "Agrega un borde de neón a tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMDAwMDAwIi8+PGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNDUiIHN0cm9rZT0iIzAwZmY4OCIgc3Ryb2tlLXdpZHRoPSI1Ii8+PC9zdmc+",
    cost: 105,
    data: { borderType: "neon", borderColor: "#00ff88", type: "border" },
  },
  {
    id: 111,
    type: "other",
    name: "Borde Dorado",
    description: "Agrega un borde dorado a tu avatar",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMDAwMDAwIi8+PGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNDUiIHN0cm9rZT0iI2ZmZDcwMCIgc3Ryb2tlLXdpZHRoPSI1Ii8+PC9zdmc+",
    cost: 110,
    data: { borderType: "gold", borderColor: "#ffd700", type: "border" },
  },
  {
    id: 112,
    type: "other",
    name: "Animación de Confeti",
    description: "Agrega una animación de confeti a tu perfil",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZmZmZmIi8+PHJlY3QgeD0iMTAiIHk9IjEwIiB3aWR0aD0iNCIgaGVpZ2h0PSI0IiBmaWxsPSIjZjAwIi8+PHJlY3QgeD0iMjUiIHk9IjI1IiB3aWR0aD0iNCIgaGVpZ2h0PSI0IiBmaWxsPSIjMGYwIi8+PHJlY3QgeD0iNDAiIHk9IjQwIiB3aWR0aD0iNCIgaGVpZ2h0PSI0IiBmaWxsPSIjMDAwZmYiLz48L3N2Zz4=",
    cost: 145,
    data: { animationType: "confetti", animationColor: "#ffffff", type: "animation" },
  },
  {
    id: 113,
    type: "other",
    name: "Animación de Lluvia",
    description: "Agrega una animación de lluvia a tu perfil",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjYWFjYWFhIi8+PHJlY3QgeD0iMTAiIHk9IjAiIHdpZHRoPSIxIiBoZWlnaHQ9IjEwIiBmaWxsPSIjMDAwMGZmIi8+PHJlY3QgeD0iMjUiIHk9IjUiIHdpZHRoPSIxIiBoZWlnaHQ9IjEwIiBmaWxsPSIjMDAwMGZmIi8+PHJlY3QgeD0iNDAiIHk9IjEwIiB3aWR0aD0iMSIgaGVpZ2h0PSIxMCIgZmlsbD0iIzAwMDBmZiIvPjwvc3ZnPg==",
    cost: 150,
    data: { animationType: "rain", animationColor: "#0000ff", type: "animation" },
  },
  {
    id: 114,
    type: "other",
    name: "Cursor Personalizado",
    description: "Cambia el cursor de tu perfil",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZmZmZmIi8+PHBhdGggZD0iTTQ1LjQ1NDUgMC4wMDAwMDFMMTAwIDU0LjU0NTVWMTBMMCAxMFYwLjAwMDAwMUw0NS40NTQ1IDAuMDAwMDAxWiIgZmlsbD0iIzAwNzhmZiIvPjwvc3ZnPg==",
    cost: 125,
    data: { cursorType: "custom", cursorURL: "url_to_cursor", type: "cursor" },
  },
  {
    id: 115,
    type: "other",
    name: "Fuente Especial",
    description: "Cambia la fuente de tu perfil",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZmZmZmIi8+PHRleHQgeD0iNTAiIHk9IjYwIiBmb250LXNpemU9IjE2IiB0ZXh0LWFuY2hvciA9Im1pZGRsZSIgZmlsbD0iIzAwMDAwMCIgZm9udC1mYW1pbHk9IkFyaWFsIj5UZXh0bzwvdGV4dD48L3N2Zz4=",
    cost: 135,
    data: { fontType: "special", fontName: "Arial", type: "font" },
  },
  {
    id: 116,
    type: "other",
    name: "Efecto de Partículas",
    description: "Agrega un efecto de partículas a tu perfil",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMDAwMDAwIi8+PGNpcmNsZSBjeD0iMjAiIGN5PSIyMCIgcj0iMSIgZmlsbD0iI2ZmZiIvPjxjaXJjbGUgY3g9IjgwIiBjeT0iNzUiIHI9IjEiIGZpbGw9IiNmZmYiLz48L3N2Zz4=",
    cost: 155,
    data: { particleType: "stars", particleColor: "#ffffff", type: "particle" },
  },
  {
    id: 117,
    type: "other",
    name: "Sonido de Fondo",
    description: "Agrega una melodía de fondo a tu perfil",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZmZmZmIi8+PHBhdGggZD0iTTI1IDQwbDEwLTEwdjQwbC0xMC0xMHYtMjB6TTQ1IDQwbDEwLTEwdjQwbC0xMC0xMHYtMjB6TTY1IDQwbDEwLTEwdjQwbC0xMC0xMHYtMjB6IiBmaWxsPSIjMDAwMDAwIi8+PC9zdmc+",
    cost: 160,
    data: { soundType: "music", soundURL: "url_to_sound", type: "sound" },
  },
  {
    id: 118,
    type: "other",
    name: "Efecto de Texto 3D",
    description: "Agrega un efecto 3D a tu texto",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZmZmZmIi8+PHRleHQgeD0iNTAiIHk9IjYwIiBmb250LXNpemU9IjE2IiB0ZXh0LWFuY2hvciA9Im1pZGRsZSIgZmlsbD0iIzAwMDAwMCI+M0Q8L3RleHQ+PC9zdmc+",
    cost: 140,
    data: { textEffect: "3d", textColor: "#000000", type: "textEffect" },
  },
  {
    id: 119,
    type: "other",
    name: "Efecto de Texto Sombreado",
    description: "Agrega un efecto de sombra a tu texto",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjZmZmZmZmIi8+PHRleHQgeD0iNTEiIHk9IjYxIiBmb250LXNpemU9IjE2IiB0ZXh0LWFuY2hvciA9Im1pZGRsZSIgZmlsbD0iIzAwMDAwMCI+VGV4dG88L3RleHQ+PHRleHQgeD0iNTAiIHk9IjYwIiBmb250LXNpemU9IjE2IiB0ZXh0LWFuY2hvciA9Im1pZGRsZSIgZmlsbD0iI2JiYmJiYiI+VGV4dG88L3RleHQ+PC9zdmc+",
    cost: 130,
    data: { textEffect: "shadow", textColor: "#bbbbbb", type: "textEffect" },
  },
  {
    id: 120,
    type: "other",
    name: "Efecto de Texto Neón",
    description: "Agrega un efecto de neón a tu texto",
    image:
      "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDEwMCAxMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiBmaWxsPSIjMDAwMDAwIi8+PHRleHQgeD0iNTAiIHk9IjYwIiBmb250LXNpemU9IjE2IiB0ZXh0LWFuY2hvciA9Im1pZGRsZSIgZmlsbD0iIzAwZmY4OCI+VGV4dG88L3RleHQ+PC9zdmc+",
    cost: 150,
    data: { textEffect: "neon", textColor: "#00ff88", type: "textEffect" },
  },
]

// Avatares predefinidos gratuitos
export const defaultAvatars = [
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Garland",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Princess",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Midnight",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Snuggles",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Cuddles",
  "https://api.dicebear.com/7.x/avataaars/svg?seed=Dusty",
]

export const userLevels: UserLevel[] = [
  { level: 1, name: "Espectador Novato", pointsRequired: 0, badge: "🎬" },
  { level: 2, name: "Cinéfilo Aficionado", pointsRequired: 100, badge: "🍿" },
  { level: 3, name: "Crítico Amateur", pointsRequired: 250, badge: "⭐" },
  { level: 4, name: "Experto en Cine", pointsRequired: 500, badge: "🎭" },
  { level: 5, name: "Maestro Cinéfilo", pointsRequired: 1000, badge: "🏆" },
  { level: 6, name: "Leyenda del Cine", pointsRequired: 2000, badge: "👑" },
  { level: 7, name: "Director Honorario", pointsRequired: 5000, badge: "🎯" },
]

export const getUserLevel = (totalPoints: number): UserLevel => {
  const levels = [...userLevels].reverse()
  return levels.find((level) => totalPoints >= level.pointsRequired) || userLevels[0]
}
